[package]
name = "nn"
authors = [ "Croisen <andrewjames.git.gan@gmail.com>" ]
version = "0.0.1"
edition = "2024"
rust-version = "1.96"
repository   = "https://github.com/croisen/nn"
readme       = "README.md"
license-file = "LICENSE"

[dependencies]
lib-matrix = { path = "./lib-matrix" }
lib-nn = { path = "./lib-nn" }
anyhow = { version = "1.0.102", default-features = false, features = ["backtrace", "std"] }
egui = { version = "0.34.3", default-features = false }
rand = { version = "0.10.1", default-features = false, features = ["std_rng", "thread_rng"] }
rayon = { version = "1.12.0", default-features = false }
serde = { version = "1.0.228", default-features = false, features = ["alloc", "derive", "rc", "serde_derive", "std"] }
serde_json = { version = "1.0.150", default-features = false, features = ["alloc", "preserve_order", "std"] }
# nnl = { version = "0.1.6", default-features = false, features = ["cpu-optimized", "openblas-src"] }

[workspace]
resolver = "2"
members = ["lib-matrix", "lib-nn"]
